import type { NotificationTypeRow, PreventionNote } from '@/features/notifications/types';

export const LOAI_THONG_BAO: NotificationTypeRow[] = [
  {
    type: 'DON_HANG',
    event: 'Nhận đơn, đang tới, đã tới, bắt đầu, chờ xác nhận',
    audience: 'BOTH',
    openTarget: 'Chi tiết đơn',
    inApp: true,
    push: true,
    hasTrigger: true,
  },
  {
    type: 'DON_HUY',
    event: 'Người chăm huỷ, chủ nuôi huỷ, hết hạn nhận, vắng mặt',
    audience: 'BOTH',
    openTarget: 'Chi tiết đơn',
    inApp: true,
    push: true,
    hasTrigger: true,
  },
  {
    type: 'DON_MOI',
    event: 'Đơn mới chờ nhận, gửi nhiều người chăm cùng lúc',
    audience: 'SITTER',
    openTarget: 'Chi tiết đơn kèm nút Nhận',
    inApp: true,
    push: true,
    hasTrigger: true,
  },
  {
    type: 'BANG_CHUNG',
    event: 'Người chăm gửi ảnh trong buổi',
    audience: 'OWNER',
    openTarget: 'Album ảnh của đơn',
    inApp: true,
    push: true,
    hasTrigger: true,
  },
  {
    type: 'DANH_GIA',
    event: 'Chủ nuôi gửi đánh giá, người chăm đáp lại',
    audience: 'BOTH',
    openTarget: 'Màn đánh giá',
    inApp: true,
    push: true,
    hasTrigger: true,
  },
  {
    type: 'NHAC_LICH',
    event: 'Sắp tới giờ dịch vụ, nhắc trước mốc hẹn',
    audience: 'BOTH',
    openTarget: 'Chi tiết đơn',
    inApp: true,
    push: true,
    hasTrigger: false,
  },
  {
    type: 'HO_SO',
    event: 'Duyệt hoặc từ chối hồ sơ, cảnh cáo, tạm ẩn và khoá hồ sơ',
    audience: 'SITTER',
    openTarget: 'Trạng thái hồ sơ',
    inApp: true,
    push: true,
    hasTrigger: true,
  },
  {
    type: 'TIN_NHAN',
    event: 'Tin nhắn mới trong hội thoại của đơn',
    audience: 'BOTH',
    openTarget: 'Màn chat của đơn',
    inApp: true,
    push: true,
    hasTrigger: false,
  },
  {
    type: 'NOI_DUNG',
    event: 'Thông báo hệ thống do quản trị viên gửi tay',
    audience: 'BOTH',
    openTarget: 'Màn thông báo của app',
    inApp: true,
    push: true,
    hasTrigger: true,
  },
  {
    type: 'TIEN_VI',
    event: 'Tiền vào ví sau 48 giờ, lệnh rút đã chuyển',
    audience: 'SITTER',
    openTarget: 'Màn ví và lịch sử giao dịch',
    inApp: true,
    push: true,
    hasTrigger: false,
  },
  {
    type: 'PHONG_BENH',
    event: 'Sắp tới hạn tiêm, tẩy giun hoặc nhỏ gáy',
    audience: 'OWNER',
    openTarget: 'Sổ phòng bệnh của bé',
    inApp: true,
    push: true,
    hasTrigger: true,
  },
  {
    type: 'KHIEU_NAI',
    event: 'Đội hỗ trợ kết luận một khiếu nại',
    audience: 'BOTH',
    openTarget: 'Hồ sơ khiếu nại',
    inApp: true,
    push: true,
    hasTrigger: true,
  },
];

export const GHI_CHU_PHONG_BENH: PreventionNote[] = [
  {
    label: 'Chu kỳ đặt ở từng lần ghi',
    desc: 'Không đặt ở hạng mục, sửa một lần không đổi các lần khác',
    value: 'từng lần ghi',
  },
  {
    label: 'Ngày tới hạn',
    desc: 'Lần mới nhất cộng chu kỳ của chính lần đó',
    value: 'ứng dụng tự tính',
  },
  {
    label: 'Ngưỡng sắp tới hạn',
    desc: 'Trước hạn chừng này thì sổ đổi màu nhắc',
    value: '7 ngày',
  },
  {
    label: 'Lúc nào tính',
    desc: 'Ứng dụng tính khi mở sổ phòng bệnh, không có tác vụ chạy nền',
    value: 'tại chỗ',
  },
  {
    label: 'Đẩy thông báo',
    desc: 'Tác vụ sáng ở máy chủ quét mũi sắp tới hạn rồi gửi tin cho chủ nuôi',
    value: 'đã có',
  },
];
